spring:
  application:
    name: backend
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:dev}"
jwt:
  secret: "${JWT_SECRET:haslomaslo11231231133131331232131312312312312312}"
  refresh-expiration: 604800000
  expiration: 3600000
